### PR TITLE
Fix safe execution

### LINKED ISSUE #117: DoSafely() doesn't actually do anything
When running a task with `DoSafely`, it never actually performs the task.

Here is an example main.go file:

```
package main

import (
	"io/ioutil"
	"log"

	"github.com/jasonlvhit/gocron"
)

func task() {
	log.Println("I am runnning task.")
	d1 := []byte("hello\ngo\n")
	ioutil.WriteFile("/tmp/dat1", d1, 0644)
}

func main() {
	s := gocron.NewScheduler()
	s.Every(3).Seconds().DoSafely(task)
	<-s.Start()
}
```

Test it out - if you swap in `Do` for `DoSafely` it works as expected, outputs to the terminal and writes the file. With `DoSafely` nothing happens.

### PR DESCRIPTION
**Pull request by preslavrachev**
Fixes #117 

Note: The recovery mechanism needed to happen inside a function wrapping the `jobFunc`. Otherwise, since the `jobFunc` is picked up and executed in a different goroutine, it will be skipped, and potential panics will escape to the main goroutine.

### CODE REVIEW

File: gocron.go [hunk 1]
```diff
@@ -115,20 +115,22 @@ func (j *Job) run() (result []reflect.Value, err error) {
 		}()
 	}
 
-	f := reflect.ValueOf(j.funcs[j.jobFunc])
-	params := j.fparams[j.jobFunc]
+	result, err = callJobFuncWithParams(j.funcs[j.jobFunc], j.fparams[j.jobFunc])
```
Comment (Streppel) [inline gocron.go]: should we ignore the error in this case?

File: gocron.go [hunk 2]
```diff
@@ -115,20 +115,22 @@ func (j *Job) run() (result []reflect.Value, err error) {
...
+	j.lastRun = time.Now()
```
Comment (Streppel) [inline gocron.go]: this undoes https://github.com/jasonlvhit/gocron/pull/116 - I believe we could put it  before calling callJobFuncWithParams? What do you think?

Comment (preslavrachev) [reply gocron.go]: Sure, I will move it before the function call. Yet, the fact that all tests ran just fine gives me an uneasy feeling.

cc @aleybovich Could you perhaps think of a unit test that ensures the correct functioning of #116?

File: gocron.go (hunk 1 above)
Comment (preslavrachev) [reply gocron.go]: Yes, seems legit. Whoever is calling the function is expected to know what the args being passed are.

**Comment by preslavrachev** [comment]
> looks great :) I've just left some comments

Comments were taken care of. Please, review again

File: gocron.go [hunk 3]
```diff
@@ -115,20 +115,22 @@ func (j *Job) run() (result []reflect.Value, err error) {
...
-	params := j.fparams[j.jobFunc]
+	j.lastRun = time.Now()
+	result, err = callJobFuncWithParams(j.funcs[j.jobFunc], j.fparams[j.jobFunc])
+	j.scheduleNextRun()
+	return
+}
+
+func callJobFuncWithParams(jobFunc interface{}, params []interface{}) ([]reflect.Value, error) {
+	f := reflect.ValueOf(jobFunc)
 	if len(params) != f.Type().NumIn() {
```
Comment (tiger5226) [inline gocron.go]: This logic is no longer accurate for `DoSafely` as a result of this PR. When you wrap the jobFunc for safely, f becomes the jobFunc and the check is wrong now. It will check the wrapped function not the passed function. So `f.Type().NumIn()` will ALWAYS return 1 regardless of the jobFunc passed into DoSafely. 

Results in any function that does not have EXACTLY 1 parameter failing this check and not running.

Comment (Streppel) [reply gocron.go]: @tiger5226 we will be deprecating DoSafely in a few days as we will stop bubbling panics up the chain, thus there is no need for it anymore (it'll be the default behavior of Do)
